[package]
name = "long_process"
version = "0.1.0"
authors = ["Luc Hogie"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.7"
crossbeam-utils = "0.7.2"
